### ISSUE TITLE
Current BT-WEB bugs/fixes:

### ISSUE THREAD

**Issue by dchen150** [ubc-biztech/bt-web#102]
- [x] Need to disable buttons when creating new event, and redirect out of page after
- [x] Need to disable buttons when editing event
- [x] Refresh page on delete event
- [x] Page Loading
- [x] Shouldn't be able to edit slug when updating event (or it needs to work)
- [ ] (for members) Need to remove “create event” in the toolbar for creating new events

**Comment by ianmah** [comment]
Refresh page on delete event is already fixed

**Comment by ianmah** [comment]
#106 fixes Shouldn't be able to edit slug when updating event (or it needs to work)

**Comment by ad2969** [comment]
I realize for
>  (for members) Need to remove “create event” in the toolbar for creating new events
may not be necessary since the designs on figma don't really include the nav bar anymore..?
