### ISSUE TITLE
add longitude/latitude to create/edit event

### ISSUE THREAD

**Issue by dchen150** [ubc-biztech/bt-web#112]
allow execs to add longitude/latitude to location

**Comment by ad2969** [comment]
Could potentially add some geocoding from mapbox/google maps or something...

**Comment by dchen150** [comment]
> Could potentially add some geocoding from mapbox/google maps or something...

LOL like LHD? click on the map and make it fill out the location fields? i feel like it's a lot of work for a small thing but could be something to implement in the future?

**Comment by ad2969** [comment]
There doesn't need to be a map.. It should help convert text address into long lat
https://developers.google.com/maps/documentation/geocoding/start

**Comment by dchen150** [comment]
ah wouldn't it require a pretty specific kind of input? one that google recognizes, which would also require google places autocomplete, or the execs to be very exact with theirf input
