### ISSUE TITLE
Search Event Table

### ISSUE THREAD

**Issue by ianmah** [ubc-biztech/bt-web#27]
Add a searchbar to the event page that searches based on first/last name or student id

Should be very fast - update the table as you type

Look into libraries for this

**Comment by joshflchan** [comment]
- **https://github.com/algolia/react-instantsearch**
- https://github.com/elastic/search-ui
- https://github.com/geobde/react-find
- https://github.com/searchkit/searchkit

after testing the demos of each library, find that search performance is approximately the same
using `react-instantsearch` as seems the most reliable based on documentation and repo
